In [1]:
# Q.1:- Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
# Ans:-
import numpy as np

# Create the array
arr = np.arange(6)

# Print the array and its data type
print("Array:", arr)
print("Data type:", arr.dtype)


Array: [0 1 2 3 4 5]
Data type: int64


In [14]:
# Q.2:- Given a NumPy array 'arr', check if its data type is float64.
      # arr = np. array([1.5,2.6,3.7])
# Ans:- 
import numpy as np

# Create the array
arr = np.  array([1.5,2.6,3.7])

# Check if the data type is float64
is_float64 = arr.dtype == np.float64

print("Is the data type float64?", is_float64)


Is the data type float64? True


In [15]:
# Q.3:- Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
# Ans:-
import numpy as np

# Create the array with complex128 data type
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)

# Print the array and its data type
print("Array:", arr)
print("Data type:", arr.dtype)



Array: [1.+2.j 3.+4.j 5.+6.j]
Data type: complex128


In [17]:
# Q.4:- Convert an existing NumPy array 'arr' of integers to float32 data type.
# Ans:-
import numpy as np

# Example existing array of integers
arr = np.array([1, 2, 3, 4, 5])

# Convert the array to float32
arr_float32 = arr.astype(np.float32)

# Print the new array and its data type
print("Array with float32 data type:", arr_float32)
print("Data type:", arr_float32.dtype)


Array with float32 data type: [1. 2. 3. 4. 5.]
Data type: float32


In [ ]:
# Q.5:-Given a NumPy array 'arr' with float64 data type , convert it to float32 to reduce decimal precision.
# Ans:- 
import numpy as np

# Example existing array with float64 data type
arr = np.array([1.123456789, 2.987654321, 3.456789123], dtype=np.float64)

# Convert the array to float32
arr_float32 = arr.astype(np.float32)

# Print the new array and its data type
print("Array with float32 data type:", arr_float32)
print("Data type:", arr_float32.dtype)


In [18]:
# Q.6:- Write a function array_attributes that takes a NumPy array as input and returns its shape, size,and data type.
# Ans:-
import numpy as np

def array_attributes(arr):
    # Get the shape, size, and data type of the array
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    
    return shape, size, dtype

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, size, dtype = array_attributes(arr)

print("Shape:", shape)
print("Size:", size)
print("Data type:", dtype)


Shape: (2, 3)
Size: 6
Data type: int64


In [19]:
# Q.7:- Create a function array_dimension that takes a NumPy array as input and return its shapes, size,and data type.
# Ans:- 
import numpy as np

def array_dimension(arr):
    # Get the shape, size, and data type of the array
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    
    return shape, size, dtype

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, size, dtype = array_dimension(arr)

print("Shape:", shape)
print("Size:", size)
print("Data type:", dtype)


Shape: (2, 3)
Size: 6
Data type: int64


In [20]:
# Q.8:- Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.
# Ans:-
import numpy as np

def item_size_info(arr):
    # Get the size of one array element in bytes
    item_size = arr.itemsize
    
    # Calculate the total size in bytes
    total_size = arr.nbytes
    
    return item_size, total_size

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
item_size, total_size = item_size_info(arr)

print("Item size (bytes):", item_size)
print("Total size (bytes):", total_size)


Item size (bytes): 4
Total size (bytes): 24


In [21]:
# Q.9:- Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
# Ans:-
import numpy as np

def array_strides(arr):
    # Get the strides of the array
    strides = arr.strides
    
    return strides

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(arr)

print("Strides:", strides)


Strides: (24, 8)


In [22]:
# Q.10:- Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.
# Ans:-
import numpy as np

def shape_stride_relationship(arr):
    # Get the shape of the array
    shape = arr.shape
    
    # Get the strides of the array
    strides = arr.strides
    
    return shape, strides

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride_relationship(arr)

print("Shape:", shape)
print("Strides:", strides)


Shape: (2, 3)
Strides: (24, 8)


In [1]:
# Q.11:-Create a function 'create_zeros_array' that takes taken an integer 'n' as input and returns a NumPy array of  zeros with 'n' elements.
# Ans:-
import numpy as np

def create_zeros_array(n):
    # Create a NumPy array of zeros with n elements
    zeros_array = np.zeros(n)
    
    return zeros_array

# Example usage:
n = 5
zeros_array = create_zeros_array(n)

print("Zeros array:", zeros_array)


Zeros array: [0. 0. 0. 0. 0.]


In [2]:
# Q.12:- Write a function 'create_ones_matrix' that takes integers 'rows' and 'cols' as inputs and generates a 2D NumPy array filled with ones of  size 'rows x cols'.
# Ans:-
import numpy as np

def create_ones_matrix(rows, cols):
    # Create a 2D NumPy array filled with ones
    ones_matrix = np.ones((rows, cols))
    
    return ones_matrix

# Example usage:
rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)

print("Ones matrix:\n", ones_matrix)


Ones matrix:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
# Q.13:- Write a function 'generate_range_array' that takes threee integers start,stop, and step as arguments and creates a NumPy array with a range starting from 'start',ending at stop(exclusive),and with the specified 'step'.
# Ans:-
import numpy as np

def generate_range_array(start, stop, step):
    # Create a NumPy array with the specified range
    range_array = np.arange(start, stop, step)
    
    return range_array

# Example usage:
start = 0
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)

print("Range array:", range_array)


Range array: [0 2 4 6 8]


In [6]:
#Q.14:- Design a function 'Generate_linear_space' that takes two floats 'start','stop'and an integers 'num'as arguments and generates a NumPy array with num equally spaced values between 'start'and 'stop'(inclusive).
# Ans:-
import numpy as np

def generate_linear_space(start, stop, num):
    # Create a NumPy array with num equally spaced values between start and stop
    linear_space_array = np.linspace(start, stop, num)
    
    return linear_space_array

# Example usage:
start = 0.0
stop = 1.0
num = 5
linear_space_array = generate_linear_space(start, stop, num)

print("Linear space array:", linear_space_array)


Linear space array: [0.   0.25 0.5  0.75 1.  ]


In [7]:
# Q.15:-Create a function 'create_identity_matrix' that takes 'n' as inputs and generates a square identity matrix of size 'n*n' using 'numpy.eye'.
# Ans:- 
import numpy as np

def create_identity_matrix(n):
    # Create a square identity matrix of size n x n
    identity_matrix = np.eye(n)
    
    return identity_matrix

# Example usage:
n = 4
identity_matrix = create_identity_matrix(n)

print("Identity matrix:\n", identity_matrix)


Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
# Q.16:- Write a function that takes a python list and converts it into a NumPy array.
# Ans:-
import numpy as np

def list_to_numpy_array(py_list):
    # Convert the Python list to a NumPy array
    np_array = np.array(py_list)
    
    return np_array

# Example usage:
py_list = [1, 2, 3, 4, 5]
np_array = list_to_numpy_array(py_list)

print("NumPy array:", np_array)


NumPy array: [1 2 3 4 5]


In [10]:
#Q.17:- Create a NumPy array and demonstrate the use of 'numpy.view' to create a new array object with the same data.
# Ans:-
import numpy as np

# Create an initial NumPy array
original_array = np.array([1, 2, 3, 4, 5])

# Create a new view of the original array
view_array = original_array.view()

# Modify the view array
view_array[0] = 10

# Print the original array and the view array to show that both share the same data
print("Original array:", original_array)
print("View array:", view_array)


Original array: [10  2  3  4  5]
View array: [10  2  3  4  5]


In [11]:
# Q.18:- Write a function that takes two NumPy array and concatenates them along a specified axis.
# Ans:-
import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):
    # Concatenate the two arrays along the specified axis
    concatenated_array = np.concatenate((arr1, arr2), axis=axis)
    
    return concatenated_array

# Example usage:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
axis = 0  # Concatenate along rows

result = concatenate_arrays(arr1, arr2, axis)

print("Concatenated array:\n", result)


Concatenated array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [12]:
# Q.19:- Create two NumPy array with different shapes and concatenate them horizontally using 'numpy.concatenate".
# Ans:- 
import numpy as np

# Create two NumPy arrays with compatible shapes for horizontal concatenation
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8],
                 [9, 10]])

# Concatenate the arrays horizontally (axis=1)
concatenated_array = np.concatenate((arr1, arr2), axis=1)

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Concatenated array:\n", concatenated_array)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8]
 [ 9 10]]
Concatenated array:
 [[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [13]:
# Q.20:- Write a function that vertically stacks multiple Numpy arrays given as list.
# Ans:-
import numpy as np

def vertical_stack_arrays(arrays):
    # Vertically stack the list of NumPy arrays
    stacked_array = np.vstack(arrays)
    
    return stacked_array

# Example usage:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

arr3 = np.array([[13, 14, 15]])

arrays = [arr1, arr2, arr3]

result = vertical_stack_arrays(arrays)

print("Vertically stacked array:\n", result)


Vertically stacked array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [14]:
# Q.21:- Write a Python function using NumPy to create an array of integers within a specified range (inclusives) with a given step size.
# Ans:-
import numpy as np

def create_range_array(start, stop, step):
    """
    Create a NumPy array of integers within the specified range (inclusive) with a given step size.

    Parameters:
    - start (int): The starting value of the range.
    - stop (int): The ending value of the range (inclusive).
    - step (int): The step size between consecutive values.

    Returns:
    - np.ndarray: A NumPy array with integers from start to stop (inclusive) with the given step size.
    """
    # Generate an array with values from start to stop (inclusive) with the specified step
    range_array = np.arange(start, stop + 1, step)
    
    return range_array

# Example usage:
start = 1
stop = 10
step = 2
result = create_range_array(start, stop, step)

print("Range array:", result)


Range array: [1 3 5 7 9]


In [15]:
# Q.22:- Write a python function using NumPy to generate an array of 10 equally spaced values betwwen 0 and 1(inclusive). 
# Ans:-
import numpy as np

def generate_equally_spaced_array(start, stop, num_values):
    """
    Generate a NumPy array of equally spaced values between start and stop (inclusive).

    Parameters:
    - start (float): The starting value of the range.
    - stop (float): The ending value of the range (inclusive).
    - num_values (int): The number of equally spaced values to generate.

    Returns:
    - np.ndarray: A NumPy array with equally spaced values from start to stop (inclusive).
    """
    # Generate the array with equally spaced values
    spaced_array = np.linspace(start, stop, num_values)
    
    return spaced_array

# Example usage:
start = 0
stop = 1
num_values = 10
result = generate_equally_spaced_array(start, stop, num_values)

print("Equally spaced array:", result)


Equally spaced array: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [16]:
# Q.23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000(inclusive).
# Ans:-
import numpy as np

def generate_logarithmically_spaced_array(start, stop, num_values):
    """
    Generate a NumPy array of logarithmically spaced values between start and stop (inclusive).

    Parameters:
    - start (float): The starting value of the range (must be greater than 0).
    - stop (float): The ending value of the range (must be greater than start).
    - num_values (int): The number of logarithmically spaced values to generate.

    Returns:
    - np.ndarray: A NumPy array with logarithmically spaced values from start to stop (inclusive).
    """
    # Generate the array with logarithmically spaced values
    log_spaced_array = np.logspace(np.log10(start), np.log10(stop), num_values)
    
    return log_spaced_array

# Example usage:
start = 1
stop = 1000
num_values = 5
result = generate_logarithmically_spaced_array(start, stop, num_values)

print("Logarithmically spaced array:", result)


Logarithmically spaced array: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [17]:
# Q.24:- create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random  integers between 1 and 100.
# ans:-
import numpy as np
import pandas as pd

# Generate a NumPy array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(5, 3))

# Create a Pandas DataFrame from the NumPy array
df = pd.DataFrame(array, columns=['Column1', 'Column2', 'Column3'])

print("Pandas DataFrame:\n", df)


Pandas DataFrame:
    Column1  Column2  Column3
0       64       13       76
1       36       92       27
2       36       70       57
3       31       88       31
4       23       46       65


In [18]:
# Q.25:- Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. use Numpy operations within the Pandas DataFrame.
#Ans :-
import pandas as pd
import numpy as np

def replace_negative_values(df, column_name):
    """
    Replace all negative values in a specified column of a Pandas DataFrame with zeros.

    Parameters:
    - df (pd.DataFrame): The DataFrame in which to replace negative values.
    - column_name (str): The name of the column in which to replace negative values.

    Returns:
    - pd.DataFrame: The DataFrame with negative values replaced by zeros in the specified column.
    """
    # Replace negative values with zeros using NumPy's where function
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    
    return df

# Example usage:
data = {
    'A': [1, -2, 3, -4, 5],
    'B': [6, 7, -8, 9, -10]
}

df = pd.DataFrame(data)

print("Original DataFrame:\n", df)

df_modified = replace_negative_values(df, 'A')

print("\nDataFrame after replacing negative values in column 'A':\n", df_modified)


Original DataFrame:
    A   B
0  1   6
1 -2   7
2  3  -8
3 -4   9
4  5 -10

DataFrame after replacing negative values in column 'A':
    A   B
0  1   6
1  0   7
2  3  -8
3  0   9
4  5 -10


In [1]:
# Q.26:- Access the #rd element from the given NumPy array.
 #        arr  = np.array([10,20,30,40,50])
  #  Ans:-
import numpy as np

# Define the NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Access the 3rd element (index 2)
third_element = arr[2]

print("The 3rd element is:", third_element)


The 3rd element is: 30


In [2]:
# Q.27:- Retrive the element at index(1,2) from the 2D NumPy array.
#        arr_2d =np.array ([[1,2,3],[ 4,5,6],[7,8,9]])
# ans:-
import numpy as np

# Define the 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Retrieve the element at index (1, 2)
element = arr_2d[1, 2]

print("The element at index (1, 2) is:", element)


The element at index (1, 2) is: 6


In [3]:
# Q.28.:- Using boolean indexing,extraction greater than 5 from the given NumPy array.
#                 arr = np.array([3,8,2,10,5,7])
# Ans:-
import numpy as np

# Define the NumPy array
arr = np.array([3, 8, 2, 10, 5, 7])

# Create a boolean mask where elements are greater than 5
mask = arr > 5

# Use the boolean mask to extract elements greater than 5
filtered_elements = arr[mask]

print("Elements greater than 5:", filtered_elements)


Elements greater than 5: [ 8 10  7]


In [4]:
# Q.29:- Perform basic slicing to extract elements from index 2 to 5(inclusive) from the given NumPy array.
#                            arr = np.array([1,2,3,4,5,6,7,8,9])
# Ans:-
import numpy as np

# Define the NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Extract elements from index 2 to 5 (inclusive)
sliced_elements = arr[2:6]

print("Elements from index 2 to 5 (inclusive):", sliced_elements)


Elements from index 2 to 5 (inclusive): [3 4 5 6]


In [5]:
# Q.30:- Slice the 2D Numpy array to extract the sub- array'[[2,3],[5,6]]'from the given array.
#          arr_2D = np.array([1,2,3],[4,5,6],[7,8,9]]).
# Ans:-
import numpy as np

# Define the 2D NumPy array
arr_2D = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Slice to extract the sub-array [[2, 3], [5, 6]]
sub_array = arr_2D[1:3, 1:3]

print("Extracted sub-array:\n", sub_array)


Extracted sub-array:
 [[5 6]
 [8 9]]


In [1]:
# Q.31:- Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
# Ans:-
import numpy as np

def extract_elements_by_indices(array_2d, indices):
    """
    Extract elements from a 2D NumPy array based on indices provided in another array.

    Parameters:
    - array_2d (np.ndarray): The 2D array from which to extract elements.
    - indices (np.ndarray): An array of indices to extract elements. Each element should be a tuple (row_index, column_index).

    Returns:
    - np.ndarray: An array of extracted elements.
    """
    # Convert the indices array to a list of tuples
    index_tuples = [tuple(index) for index in indices]
    
    # Extract elements based on the provided indices
    extracted_elements = array_2d[tuple(zip(*index_tuples))]
    
    return extracted_elements

# Example usage:
arr_2D = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

# Indices to extract: (0, 1), (1, 2), (2, 0)
indices = np.array([[0, 1], [1, 2], [2, 0]])

# Extract elements based on the provided indices
result = extract_elements_by_indices(arr_2D, indices)

print("Extracted elements:", result)


Extracted elements: [20 60 70]


In [2]:
# Q.32:- Create a Numpy function that filters elements greater than a threshold from a given 1D array using boolean indexing
# Ans:-
import numpy as np

def filter_elements_greater_than(array, threshold):
    """
    Filter elements greater than a specified threshold from a 1D NumPy array using boolean indexing.

    Parameters:
    - array (np.ndarray): The 1D array to filter.
    - threshold (float): The threshold value to compare against.

    Returns:
    - np.ndarray: A 1D array with elements greater than the threshold.
    """
    # Create a boolean mask where elements are greater than the threshold
    mask = array > threshold
    
    # Use the boolean mask to filter elements
    filtered_elements = array[mask]
    
    return filtered_elements

# Example usage:
arr = np.array([1, 5, 8, 3, 10, 6])
threshold = 5

result = filter_elements_greater_than(arr, threshold)

print("Elements greater than", threshold, ":", result)


Elements greater than 5 : [ 8 10  6]


In [3]:
# Q.33. Develop a Numpy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
# Ans:-
import numpy as np

def extract_elements_from_3d_array(array_3d, row_indices, col_indices, depth_indices):
    """
    Extract specific elements from a 3D NumPy array using indices provided in three separate arrays.

    Parameters:
    - array_3d (np.ndarray): The 3D array from which to extract elements.
    - row_indices (np.ndarray): Array of row indices.
    - col_indices (np.ndarray): Array of column indices.
    - depth_indices (np.ndarray): Array of depth indices.

    Returns:
    - np.ndarray: Array of extracted elements.
    """
    # Use advanced indexing to extract elements based on provided indices
    extracted_elements = array_3d[row_indices, col_indices, depth_indices]
    
    return extracted_elements

# Example usage:
array_3d = np.array([[[10, 20, 30],
                      [40, 50, 60],
                      [70, 80, 90]],

                     [[11, 21, 31],
                      [41, 51, 61],
                      [71, 81, 91]],

                     [[12, 22, 32],
                      [42, 52, 62],
                      [72, 82, 92]]])

# Indices to extract
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])
depth_indices = np.array([2, 1, 0])

# Extract elements based on the provided indices
result = extract_elements_from_3d_array(array_3d, row_indices, col_indices, depth_indices)

print("Extracted elements:", result)


Extracted elements: [60 81 12]


In [4]:
# Q.34:- Write a Numpy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
#Ans:-
import numpy as np

def filter_elements_with_conditions(array, condition1, condition2):
    """
    Return elements from the array where both conditions are satisfied using boolean indexing.

    Parameters:
    - array (np.ndarray): The array to filter.
    - condition1 (np.ndarray): A boolean array representing the first condition.
    - condition2 (np.ndarray): A boolean array representing the second condition.

    Returns:
    - np.ndarray: An array of elements where both conditions are satisfied.
    """
    # Ensure conditions are of the same shape as the array
    if condition1.shape != array.shape or condition2.shape != array.shape:
        raise ValueError("Condition arrays must have the same shape as the input array.")
    
    # Combine conditions using logical AND
    combined_condition = condition1 & condition2
    
    # Use the combined condition to filter elements
    filtered_elements = array[combined_condition]
    
    return filtered_elements

# Example usage:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Define conditions
condition1 = arr > 3
condition2 = arr % 2 == 0

# Filter elements where both conditions are satisfied
result = filter_elements_with_conditions(arr, condition1, condition2)

print("Filtered elements:", result)


Filtered elements: [4 6 8]


In [5]:
# Q.35:- Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
# Ans:-
import numpy as np

def extract_elements_from_2d_array(array_2d, row_indices, col_indices):
    """
    Extract specific elements from a 2D NumPy array using row and column indices provided in separate arrays.

    Parameters:
    - array_2d (np.ndarray): The 2D array from which to extract elements.
    - row_indices (np.ndarray): Array of row indices.
    - col_indices (np.ndarray): Array of column indices.

    Returns:
    - np.ndarray: Array of extracted elements.
    """
    # Ensure the row_indices and col_indices arrays have the same length
    if len(row_indices) != len(col_indices):
        raise ValueError("Row indices and column indices must have the same length.")
    
    # Extract elements using advanced indexing
    extracted_elements = array_2d[row_indices, col_indices]
    
    return extracted_elements

# Example usage:
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60],
                     [70, 80, 90]])

# Row and column indices to extract
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])

# Extract elements based on the provided indices
result = extract_elements_from_2d_array(array_2d, row_indices, col_indices)

print("Extracted elements:", result)


Extracted elements: [20 60 70]


In [6]:
# Q.36:- Given an array arr of shape(3,3),add a scalar value of 5 to each element using NumPy broadcasting.
# Ans:-
import numpy as np

# Define the 2D NumPy array with shape (3, 3)
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Scalar value to add
scalar = 5

# Add the scalar to each element of the array using broadcasting
result = arr + scalar

print("Array after adding scalar value of 5:\n", result)


Array after adding scalar value of 5:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [12]:
# Q.37:- Consider two arrays arr1 of shape(1,3) and arr2 of shape(3,4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.
# Ans:-
import numpy as np

# Define the arrays
arr1 = np.array([2, 3, 4])  # Shape (3,)
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])  # Shape (3, 4)

# Reshape arr1 to shape (3, 1) for broadcasting
arr1_reshaped = arr1.reshape(3, 1)

# Multiply each row of arr2 by the corresponding element in arr1 using broadcasting
result = arr2 * arr1_reshaped

print("Resulting array:\n", result)


Resulting array:
 [[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [13]:
# Q.38:- Given a 1D array arr1 of shape(1,4) and a 2D array arr2 of shape(4,3),add arr1 to each row of arr2 using Numpy broadcasting.
# Ans:-
import numpy as np

# Define the arrays
arr1 = np.array([[1, 2, 3, 4]])  # Shape (1, 4)
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])  # Shape (4, 3)

# Reshape arr1 to be compatible for broadcasting
arr1_reshaped = arr1.reshape(1, 4)  # Ensure arr1 has shape (1, 4)

# Add arr1 to each row of arr2
result = arr2 + arr1_reshaped[:, :arr2.shape[1]]

print("Resulting array:\n", result)


Resulting array:
 [[ 6  8 10]
 [ 9 11 13]
 [12 14 16]
 [15 17 19]]


In [14]:
# Q.39:-Consider two arrays arr1 of shape(3,1) and arr2 of shape(1,3).Add these arrays using NumPy broadcasting.
# Ans:-
import numpy as np

# Define the arrays
arr1 = np.array([[1], [2], [3]])  # Shape (3, 1)
arr2 = np.array([[4, 5, 6]])       # Shape (1, 3)

# Add the arrays using broadcasting
result = arr1 + arr2

print("Resulting array:\n", result)


Resulting array:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [15]:
# Q.40:- Given arrays arr1 of shape(2,3) and arr2 of shape (2,2),perform multiplication using NumPy broadcasting.Handle the shape incompatibility.
# Ans:-
import numpy as np

# Define the arrays
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])   # Shape (2, 3)
arr2 = np.array([[7, 8],
                 [9, 10]])    # Shape (2, 2)

# Reshape arr2 to make it compatible with arr1 for broadcasting
arr2_reshaped = arr2.reshape(2, 1, 2)  # Shape (2, 1, 2)

# Perform the multiplication
# Use broadcasting: arr1 (2, 3) and arr2_reshaped (2, 1, 2) will broadcast to (2, 3, 2)
result = arr1[:, :, np.newaxis] * arr2_reshaped

# Since the multiplication creates a 3D array, we can sum along the last axis if needed
# For this example, we will leave it as a 3D array
print("Resulting array:\n", result)


Resulting array:
 [[[ 7  8]
  [14 16]
  [21 24]]

 [[36 40]
  [45 50]
  [54 60]]]


In [1]:
# Q.41:- Calculate column-wise mean for the given arrry:
#               arr = np.array([1,2,3],[4,5,6,]])
# Ans:-
import numpy as np

# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Calculate the column-wise mean
column_wise_mean = np.mean(arr, axis=0)

print("Column-wise mean:", column_wise_mean)


Column-wise mean: [2.5 3.5 4.5]


In [2]:
# Q.42:-Find maximum value in each row of the given array:
#        arr = np.array([[1,2,3],[4,5,6]])
# Ans:-
import numpy as np

# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Calculate the maximum value in each row
row_max_values = np.max(arr, axis=1)

print("Maximum value in each row:", row_max_values)


Maximum value in each row: [3 6]


In [3]:
# Q.43:-For the given array, find indices of maximum value in each column.
#        arr = np.array([[1,2,3],[4,5,6]])
#Ans:-
import numpy as np

# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find the indices of the maximum value in each column
indices_of_max = np.argmax(arr, axis=0)

print("Indices of maximum value in each column:", indices_of_max)


Indices of maximum value in each column: [1 1 1]


In [4]:
# Q.44:- For the given array,apply custom function to calculate moving sum along rows.
#             arr = np.array([[1,2,3],[4,5,6]])
#Ans:-
import numpy as np

def moving_sum(arr, window_size):
    """
    Compute the moving sum along rows for a given window size.
    
    Parameters:
    arr (numpy.ndarray): 2D array on which moving sum is computed.
    window_size (int): Size of the moving window.
    
    Returns:
    numpy.ndarray: Array with moving sums along rows.
    """
    num_rows, num_cols = arr.shape
    if window_size > num_cols:
        raise ValueError("Window size must be less than or equal to the number of columns")
    
    # Initialize the result array
    result = np.zeros((num_rows, num_cols - window_size + 1), dtype=int)
    
    # Compute the moving sum for each row
    for i in range(num_rows):
        for j in range(num_cols - window_size + 1):
            result[i, j] = np.sum(arr[i, j:j + window_size])
    
    return result

# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Apply the custom function with a window size of 2
window_size = 2
moving_sum_result = moving_sum(arr, window_size)

print("Moving sum along rows:\n", moving_sum_result)


Moving sum along rows:
 [[ 3  5]
 [ 9 11]]


In [5]:
# Q.45:- In the given array,check if all elements in each column are even.
#          arr = np.array([[2,4,6],[3,5,7]])
# Ans:-
import numpy as np

# Define the array
arr = np.array([[2, 4, 6],
                [3, 5, 7]])

# Check if all elements in each column are even
all_even_columns = np.all(arr % 2 == 0, axis=0)

print("All elements in each column are even:", all_even_columns)


All elements in each column are even: [False False False]


In [6]:
# Q.46:- Given a Numpy array arr,reshape it into a matrix of dimensions 'm' rows and 'n' columns. Return the reshaped matrix.
#         original_array = np.array([1,2,3,4,5,6])
# Ans:-
import numpy as np

# Define the original array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Define the desired dimensions
m = 2  # Number of rows
n = 3  # Number of columns

# Reshape the array
reshaped_matrix = original_array.reshape(m, n)

print("Reshaped matrix:\n", reshaped_matrix)


Reshaped matrix:
 [[1 2 3]
 [4 5 6]]


In [8]:
# Q.47:- Create a function that takes a matrix as input and returns the flattened array.
#        input_matrix = np.array([[1,2,3],[4,5,6]])
# Ans:-
import numpy as np

def flatten_matrix(matrix):
    """
    Flattens a 2D NumPy array into a 1D array.
    
    Parameters:
    matrix (numpy.ndarray): The 2D array to be flattened.
    
    Returns:
    numpy.ndarray: The flattened 1D array.
    """
    # Flatten the matrix
    flattened_array = matrix.flatten()
    return flattened_array

# Define the input matrix
input_matrix = np.array([[1, 2, 3],
                         [4, 5, 6]])

# Call the function and print the result
flattened_result = flatten_matrix(input_matrix)
print("Flattened array:", flattened_result)


Flattened array: [1 2 3 4 5 6]


In [9]:
# Q.48:- Write a function that concatenates two given arrays along a specified axis.
#         array1  = np.array([[1,2],[3,4]])
#          array2 = np.array([[5,6],[7,8]])
#Ans:-
import numpy as np

def concatenate_arrays(array1, array2, axis):
    """
    Concatenates two NumPy arrays along a specified axis.
    
    Parameters:
    array1 (numpy.ndarray): The first array to concatenate.
    array2 (numpy.ndarray): The second array to concatenate.
    axis (int): The axis along which to concatenate the arrays.
    
    Returns:
    numpy.ndarray: The concatenated array.
    """
    # Concatenate the arrays along the specified axis
    concatenated_array = np.concatenate((array1, array2), axis=axis)
    return concatenated_array

# Define the input arrays
array1 = np.array([[1, 2],
                   [3, 4]])
array2 = np.array([[5, 6],
                   [7, 8]])

# Specify the axis for concatenation
axis = 0  # Change to 1 for column-wise concatenation

# Call the function and print the result
result = concatenate_arrays(array1, array2, axis)
print("Concatenated array:\n", result)


Concatenated array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [10]:
# Q.49:- Create a function that splits an array into multiple sub-arrays along a specified axis.
#         Original_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
# Ans:-
import numpy as np

def split_array(array, num_splits, axis):
    """
    Splits a NumPy array into multiple sub-arrays along a specified axis.
    
    Parameters:
    array (numpy.ndarray): The array to be split.
    num_splits (int): The number of splits along the specified axis.
    axis (int): The axis along which to split the array.
    
    Returns:
    list of numpy.ndarray: The list of sub-arrays obtained from splitting the original array.
    """
    # Calculate the indices where the array should be split
    split_indices = np.array_split(array, num_splits, axis=axis)
    return split_indices

# Define the original array
original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

# Specify the number of splits and the axis for splitting
num_splits = 3  # Number of splits along the specified axis
axis = 1        # Axis along which to split (0 for rows, 1 for columns)

# Call the function and print the result
split_result = split_array(original_array, num_splits, axis)
for i, sub_array in enumerate(split_result):
    print(f"Sub-array {i}:\n{sub_array}\n")


Sub-array 0:
[[1]
 [4]
 [7]]

Sub-array 1:
[[2]
 [5]
 [8]]

Sub-array 2:
[[3]
 [6]
 [9]]



In [12]:
# Q.50:- Write a function that inserts and then deletes elements from a given array at specified indices.
#         Original_array = np.array([1,2,3,4,5])
 #          indices_to_insert = [2,4]
  #          values_to_insert = [10,11]
   #        indices_to_delete = [1,3]
    #Ans:-
import numpy as np

def modify_array(array, indices_to_insert, values_to_insert, indices_to_delete):
    """
    Inserts values into a NumPy array at specified indices and then deletes elements at specified indices.
    
    Parameters:
    array (numpy.ndarray): The original array.
    indices_to_insert (list of int): The indices at which to insert new values.
    values_to_insert (list of int): The values to be inserted.
    indices_to_delete (list of int): The indices of elements to be deleted.
    
    Returns:
    numpy.ndarray: The modified array after insertion and deletion.
    """
    # Insert values into the array
    modified_array = np.insert(array, indices_to_insert, values_to_insert)
    
    # Delete specified indices from the modified array
    modified_array = np.delete(modified_array, indices_to_delete)
    
    return modified_array

# Define the original array
original_array = np.array([1, 2, 3, 4, 5])

# Specify indices and values for insertion and deletion
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

# Call the function and print the result
result = modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print("Modified array:", result)


Modified array: [ 1 10  4 11  5]


In [14]:
# Q.51:- Create a Numpy array 'arr1' with random intergers and another arrray 'arr2' with intergers from 1 to 10. Perform element-wise addition between 'arr1' and 'arr2'.
# Ans:-
import numpy as np

# Create arr1 with random integers (e.g., 2x5 matrix with values between 0 and 9)
arr1 = np.random.randint(0, 10, size=(2, 5))

# Create arr2 with integers from 1 to 10 (reshaped to be compatible with arr1)
arr2 = np.arange(1, 6)  # 1D array with values [1, 2, 3, 4, 5]

# Ensure arr2 has the same shape as arr1 for element-wise addition
arr2 = np.tile(arr2, (2, 1))  # Tile arr2 to match the shape of arr1

# Perform element-wise addition
result = arr1 + arr2

print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("Element-wise addition result:\n", result)


arr1:
 [[9 5 4 9 1]
 [2 3 8 5 6]]
arr2:
 [[1 2 3 4 5]
 [1 2 3 4 5]]
Element-wise addition result:
 [[10  7  7 13  6]
 [ 3  5 11  9 11]]


In [15]:
# Q.52:-Generate a Numpy array 'arr1' with sequential integerrs from 10 to 1 and another array 'arr2' with integers from 1 to 10. Subtract 'arr2'from 'arr1' element-wise.
# Ans:-
import numpy as np

# Create arr1 with sequential integers from 10 to 1
arr1 = np.arange(10, 0, -1)  # [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

# Create arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)      # [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Perform element-wise subtraction
result = arr1 - arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise subtraction result:", result)


arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Element-wise subtraction result: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [16]:
# Q.53:-Create a NumPy array 'arr1' with random integers and another array 'arr2' with integers from 1 to 5.Perform element-wise multiplication between 'arr1' and 'arr2'.
# Ans:-
import numpy as np

# Create arr1 with random integers (e.g., 2x5 matrix with values between 1 and 10)
arr1 = np.random.randint(1, 10, size=(2, 5))

# Create arr2 with integers from 1 to 5 (reshaped to be compatible with arr1)
arr2 = np.arange(1, 6)  # 1D array with values [1, 2, 3, 4, 5]

# Ensure arr2 has the same shape as arr1 for element-wise multiplication
arr2 = np.tile(arr2, (2, 1))  # Tile arr2 to match the shape of arr1

# Perform element-wise multiplication
result = arr1 * arr2

print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("Element-wise multiplication result:\n", result)


arr1:
 [[8 9 3 8 3]
 [3 1 6 3 9]]
arr2:
 [[1 2 3 4 5]
 [1 2 3 4 5]]
Element-wise multiplication result:
 [[ 8 18  9 32 15]
 [ 3  2 18 12 45]]


In [17]:
# Q.54:- Generate a NumPy array 'arr1' with even integers from 2 to 10 and another array 'arr2' with intergers from 1 to 5. perform element-wise division of 'arr1' by 'arr2'.
# Ans:-
import numpy as np

# Create arr1 with even integers from 2 to 10
arr1 = np.arange(2, 11, 2)  # [2, 4, 6, 8, 10]

# Create arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)     # [1, 2, 3, 4, 5]

# Ensure arr1 and arr2 have the same shape for element-wise division
# If needed, reshape or tile arrays to ensure they are compatible for broadcasting
arr1 = np.tile(arr1, (5, 1))  # Create a 5x5 matrix by repeating arr1
arr2 = np.tile(arr2, (5, 1))  # Create a 5x5 matrix by repeating arr2

# Perform element-wise division
result = arr1 / arr2

print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("Element-wise division result:\n", result)


arr1:
 [[ 2  4  6  8 10]
 [ 2  4  6  8 10]
 [ 2  4  6  8 10]
 [ 2  4  6  8 10]
 [ 2  4  6  8 10]]
arr2:
 [[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
Element-wise division result:
 [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [18]:
# Q.55:- Create a NumPy array 'arr1' with integers from 1 to 5 and another array 'arr2' with the same numbers reveresd. Calculate the exponenntiation of 'arr1' raised to the power of 'arr2'element-wise.
# Ans:-
import numpy as np

# Create arr1 with integers from 1 to 5
arr1 = np.arange(1, 6)  # [1, 2, 3, 4, 5]

# Create arr2 with integers from 5 to 1 (reversed order)
arr2 = arr1[::-1]  # [5, 4, 3, 2, 1]

# Perform element-wise exponentiation
result = arr1 ** arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise exponentiation result:", result)


arr1: [1 2 3 4 5]
arr2: [5 4 3 2 1]
Element-wise exponentiation result: [ 1 16 27 16  5]


In [19]:
# Q.56:- Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
#        arr = np.array(['hello','world','hello', 'numpy','hello'])
# Ans:-import numpy as np

def count_substring_occurrences(arr, substring):
    # Use np.char.find to find the substring within each element of the array
    occurrences = np.char.find(arr, substring)
    # Count how many times the substring is found (i.e., not -1)
    count = np.sum(occurrences != -1)
    return count

# Example usage
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
result = count_substring_occurrences(arr, substring)

print(f"Occurrences of '{substring}':", result)


Occurrences of 'hello': 3


In [20]:
# Q.57:- Write a function that extracts uppercase characters from a NumPy array of strings.
#            arr = np.array(['hello','world','openAI, 'GPT'])
#       arr = np.array(['Hello','World','OpenAI','GPT'])
# Ans:-
import numpy as np

def extract_uppercase(arr):
    # Create an empty list to hold the uppercase characters
    uppercase_chars = []

    # Iterate over each string in the array
    for string in arr:
        # Extract uppercase characters using a list comprehension
        uppercase_chars.extend([char for char in string if char.isupper()])

    # Convert the list to a NumPy array and return
    return np.array(uppercase_chars)

# Example usage
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
result = extract_uppercase(arr)

print("Extracted uppercase characters:", result)


Extracted uppercase characters: ['H' 'W' 'O' 'A' 'I' 'G' 'P' 'T']


In [21]:
# Q.58:- Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
    #      arr = np.array(['apple','banana','grape',pineapple'])
    
#Ans:-
import numpy as np

def replace_substring(arr, old_substring, new_substring):
    # Use np.char.replace to replace occurrences of old_substring with new_substring
    replaced_array = np.char.replace(arr, old_substring, new_substring)
    return replaced_array

# Example usage
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'apple'
new_substring = 'fruit'
result = replace_substring(arr, old_substring, new_substring)

print("Original array:", arr)
print("Array after replacement:", result)


Original array: ['apple' 'banana' 'grape' 'pineapple']
Array after replacement: ['fruit' 'banana' 'grape' 'pinefruit']


In [22]:
# Q.59:- Write a function that finds the length of the longest string in a NumPy array.
#         arr=np.array(['apple','banana','grape','pineapple'])
# Ans:-
import numpy as np

def length_of_longest_string(arr):
    # Get the length of each string in the array
    lengths = np.char.str_len(arr)
    # Find the maximum length
    max_length = np.max(lengths)
    return max_length

# Example usage
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
result = length_of_longest_string(arr)

print("Length of the longest string:", result)


Length of the longest string: 9


In [23]:
# 60:- Write a function that concatenates strings in a NumPy array element-wise.
#        arr1 = np.array(['Hello','world'])
#        arr2 = np.array(['Open','AI'])
#Ans:-
import numpy as np

def concatenate_strings_elementwise(arr1, arr2):
    # Use np.char.add to concatenate strings element-wise
    concatenated_array = np.char.add(arr1, arr2)
    return concatenated_array

# Example usage
arr1 = np.array(['Hello', 'world'])
arr2 = np.array(['Open', 'AI'])
result = concatenate_strings_elementwise(arr1, arr2)

print("Concatenated array:", result)


Concatenated array: ['HelloOpen' 'worldAI']


In [24]:
# Q.61:- Create a dataset of 100 random integers between 1 and 1000. Compute the mean,median,variance, and standard deviation of the dataset using NumPy's functions.
# Ans:-
import numpy as np

# Step 1: Generate the dataset
np.random.seed(0)  # For reproducibility
dataset = np.random.randint(1, 1001, size=100)

# Step 2: Compute statistical measures
mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset)

print("Dataset:", dataset)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)


Dataset: [ 685  560  630  193  836  764  708  360   10  724  278  755  805  600
   71  473  601  397  315  706  487  552   88  175  601  850  678  538
  846   73  778  917  116  977  756  710  848  432  449  851  100  985
  178  756  798  660  148  911  424  289  962  266  698  640  545  544
  715  245  152  676  511  460  883  184   29  803  129  129  933   54
  902  551  489  757  274  336  389  618   43  443  544  889  258  322
 1000  938   58  292  871  120  780  431   83   92  897  399  612  566
  909  634]
Mean: 524.97
Median: 551.5
Variance: 82414.08910000001
Standard Deviation: 287.07854169199067


In [25]:
# 62:- Generate an array of 50 random numbers between 1 and 100.Find the 25th and 75th percentiles of the dataset.
# Ans:-
import numpy as np

# Step 1: Generate the dataset
np.random.seed(0)  # For reproducibility
data = np.random.randint(1, 101, size=50)

# Step 2: Calculate the 25th and 75th percentiles
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

print("Dataset:", data)
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)


Dataset: [ 45  48  65  68  68  10  84  22  37  88  71  89  89  13  59  66  40  88
  47  89  82  38  26  78  73  10  21  81  70  80  48  65  83 100  89  50
  30  20  20  15  40  33  66  10  58  33  32  75  24  36]
25th Percentile: 32.25
75th Percentile: 77.25


In [26]:
# 63:- Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy,s "corrcoef" function.
# Ans:-
import numpy as np

# Step 1: Create two arrays
array1 = np.array([10, 20, 30, 40, 50])
array2 = np.array([1, 2, 3, 4, 5])

# Step 2: Compute the correlation coefficient
correlation_matrix = np.corrcoef(array1, array2)
correlation_coefficient = correlation_matrix[0, 1]

print("Correlation Matrix:\n", correlation_matrix)
print("Correlation Coefficient between array1 and array2:", correlation_coefficient)


Correlation Matrix:
 [[1. 1.]
 [1. 1.]]
Correlation Coefficient between array1 and array2: 1.0


In [27]:
# Q.64:- Create two matrices and perform matrix multiplication using NumPy's 'dot' function.
# Ans:-
import numpy as np

# Step 1: Create two matrices
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[7, 8], [9, 10], [11, 12]])

# Step 2: Perform matrix multiplication
result = np.dot(matrix1, matrix2)

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Matrix Multiplication Result:\n", result)


Matrix 1:
 [[1 2 3]
 [4 5 6]]
Matrix 2:
 [[ 7  8]
 [ 9 10]
 [11 12]]
Matrix Multiplication Result:
 [[ 58  64]
 [139 154]]


In [28]:
# Q.65:- Create an array of 50 integers between 10 and 1000. calculate the 10th,50th(median),and 90th percentiles along with the first and third quartiles.
#Ans:-
import numpy as np

# Step 1: Generate the array
np.random.seed(0)  # For reproducibility
data = np.random.randint(10, 1001, size=50)

# Step 2: Calculate percentiles and quartiles
percentile_10 = np.percentile(data, 10)
percentile_50 = np.percentile(data, 50)  # This is the median
percentile_90 = np.percentile(data, 90)
first_quartile = np.percentile(data, 25)
third_quartile = np.percentile(data, 75)

print("Array:", data)
print("10th Percentile:", percentile_10)
print("50th Percentile (Median):", percentile_50)
print("90th Percentile:", percentile_90)
print("First Quartile (25th Percentile):", first_quartile)
print("Third Quartile (75th Percentile):", third_quartile)


Array: [694 569 639 202 845 773 717 369  19 733 287 764 814 609  80 482 610 406
 324 715 496 561  97 184 610 859 687 547 855  82 787 926 125 986 765 719
 857 441 458 860 109 994 187 765 807 669 157 920 433 298]
10th Percentile: 123.4
50th Percentile (Median): 610.0
90th Percentile: 859.1
First Quartile (25th Percentile): 335.25
Third Quartile (75th Percentile): 771.0


In [3]:
# Q.66:- create a NumPy array of integers and find the index of a specific element.
# Ans:-
import numpy as np

array = np.array([10, 20, 30, 40, 50])


element = 30

# Find the index of the specific element
index = np.where(array == element)[0][0]

print(f"The index of {element} is {index}")


The index of 30 is 2


In [ ]:
# Q.67:- Generate a random NumPy array and sort it in ascending order.
# Ans:-
import numpy as np

# Generate a random NumPy array of integers between 0 and 100, with 10 elements
random_array = np.random.randint(0, 100, size=10)

print("Original array:")
print(random_array)

# Sort the array in ascending order
sorted_array = np.sort(random_array)

print("\nSorted array:")
print(sorted_array)


In [4]:
# Q.68:- Filter elements >20 in the given NumPy array.
#        arr = np.array([12,25,6,42,8,30])
#Ans:-
import numpy as np

# Given array
arr = np.array([12, 25, 6, 42, 8, 30])

# Filter elements greater than 20
filtered_arr = arr[arr > 20]

print("Filtered array (elements > 20):")
print(filtered_arr)


Filtered array (elements > 20):
[25 42 30]


In [5]:
# Q.69:- Filter elemenets which are divisible by 3 from a given NumPy array.
#             arr = np.array([1,5,8,12,15])
# Ans:-
import numpy as np

# Given array
arr = np.array([1, 5, 8, 12, 15])

# Filter elements divisible by 3
filtered_arr = arr[arr % 3 == 0]

print("Filtered array (elements divisible by 3):")
print(filtered_arr)


Filtered array (elements divisible by 3):
[12 15]


In [6]:
# Q.70:- Filter elements which are >=20 and <=40 from a given NumPy array.
#           arr = np.array([10,20,30,40,50])
# Ans:-
import numpy as np

# Given array
arr = np.array([10, 20, 30, 40, 50])

# Filter elements >= 20 and <= 40
filtered_arr = arr[(arr >= 20) & (arr <= 40)]

print("Filtered array (elements >= 20 and <= 40):")
print(filtered_arr)


Filtered array (elements >= 20 and <= 40):
[20 30 40]


In [7]:
#Q.71:- For the given NumPy array,check its byte order using the 'dtype' attribute byteorder.
#         arr = np.array([1,2,3])
#Ans:-
import numpy as np

# Given array
arr = np.array([1, 2, 3])

# Check the byte order
byte_order = arr.dtype.byteorder

print(f"The byte order of the array is: '{byte_order}'")


The byte order of the array is: '='


In [8]:
# Q.72:-For the given NumPy array,perform byte swapping in place using 'byteswap()'.
#                arr = np.array([1,2,3],dtype=np.int32)
#Ans:-
import numpy as np

# Given array with dtype=np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

print("Original array:")
print(arr)
print(f"Byte order before swapping: {arr.dtype.byteorder}")

# Perform byte swapping in place
arr.byteswap(True)

print("\nArray after byte swapping:")
print(arr)
print(f"Byte order after swapping: {arr.dtype.byteorder}")


Original array:
[1 2 3]
Byte order before swapping: =

Array after byte swapping:
[16777216 33554432 50331648]
Byte order after swapping: =


In [9]:
# Q.73:-For the given NumPy array,swap its byte order without modifying the original array using 'newbyteorder()'.
#                arr = np.array([1,2,3],dtype=np.int32)
#Ans:-
import numpy as np

# Given array with dtype=np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

print("Original array:")
print(arr)
print(f"Byte order before swapping: {arr.dtype.byteorder}")

# Swap byte order without modifying the original array
swapped_arr = arr.byteswap().newbyteorder()

print("\nArray after swapping byte order (without modifying the original array):")
print(swapped_arr)
print(f"Byte order after swapping: {swapped_arr.dtype.byteorder}")

print("\nOriginal array remains unchanged:")
print(arr)


Original array:
[1 2 3]
Byte order before swapping: =

Array after swapping byte order (without modifying the original array):
[1 2 3]
Byte order after swapping: >

Original array remains unchanged:
[1 2 3]


In [10]:
#Q.74:- For the given NumPy array and swap its byte order conditionally based on system endianness using 'newbyteorder()'.
#          arr = np.array([1,2,3] , dtype = np.int32)
# Ans:-
import numpy as np

# Given array with dtype=np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

print("Original array:")
print(arr)
print(f"Byte order before swapping: {arr.dtype.byteorder}")

# Determine system endianness and conditionally swap byte order
if arr.dtype.byteorder == '=':  # Native byte order
    swapped_arr = arr.byteswap().newbyteorder()
else:
    swapped_arr = arr

print("\nArray after conditional byte order swapping:")
print(swapped_arr)
print(f"Byte order after conditional swapping: {swapped_arr.dtype.byteorder}")


Original array:
[1 2 3]
Byte order before swapping: =

Array after conditional byte order swapping:
[1 2 3]
Byte order after conditional swapping: >


In [11]:
# Q.75:- For the given NumPy array,check if byte swapping is necessary for the current system using 'dtype'attribute 'byteorder'.
#         arr = np.array([1,2,3] , dtype = np.int32.
#Ans:-
import numpy as np

# Given array with dtype=np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Check the byte order
byte_order = arr.dtype.byteorder

# Determine if byte swapping is necessary
if byte_order == '=':
    print("Byte swapping is not necessary; the array is already in the system's native byte order.")
elif byte_order == '<':
    print("The array is in little-endian format.")
elif byte_order == '>':
    print("The array is in big-endian format.")
else:
    print("Byte swapping is not applicable (e.g., for non-numeric types).")


Byte swapping is not necessary; the array is already in the system's native byte order.


In [12]:
# Q.76:- Create a NumPy array 'arr1' with values from 1 to 10. create a copy of 'arr1'named 'copy_arr1' and modify an element in 'copy_arr'.Check if modifying 'copy_arr' affects 'arr1'.
# Ans:-
import numpy as np

# Create a NumPy array 'arr1' with values from 1 to 10
arr1 = np.arange(1, 11)

# Create a copy of 'arr1' named 'copy_arr1'
copy_arr1 = arr1.copy()

# Modify an element in 'copy_arr1'
copy_arr1[0] = 99  # For example, change the first element to 99

# Check if modifying 'copy_arr1' affects 'arr1'
print("Original array (arr1):")
print(arr1)

print("\nModified copy (copy_arr1):")
print(copy_arr1)

# Determine if 'arr1' has been affected
if np.array_equal(arr1, copy_arr1):
    print("\nModifying 'copy_arr1' did affect 'arr1'.")
else:
    print("\nModifying 'copy_arr1' did not affect 'arr1'.")


Original array (arr1):
[ 1  2  3  4  5  6  7  8  9 10]

Modified copy (copy_arr1):
[99  2  3  4  5  6  7  8  9 10]

Modifying 'copy_arr1' did not affect 'arr1'.


In [1]:
# Q.77:-Create a 2D NumPy array 'matrix' of shapes(3,3) with random integers. Extract a slice 'view_slice' from the matrix.Modify an element in'view_slice'and observe if it changes the original'matrix'.
#ans:-
import numpy as np

# Create a 2D NumPy array 'matrix' with random integers between 0 and 10, of shape (3, 3)
matrix = np.random.randint(0, 10, size=(3, 3))

print("Original matrix:")
print(matrix)

# Extract a slice 'view_slice' from the matrix (e.g., the submatrix consisting of the first two rows and columns)
view_slice = matrix[:2, :2]

print("\nSlice (view_slice) before modification:")
print(view_slice)

# Modify an element in 'view_slice'
view_slice[0, 0] = 99

print("\nSlice (view_slice) after modification:")
print(view_slice)

print("\nOriginal matrix after modifying 'view_slice':")
print(matrix)


Original matrix:
[[0 7 0]
 [1 2 7]
 [1 8 5]]

Slice (view_slice) before modification:
[[0 7]
 [1 2]]

Slice (view_slice) after modification:
[[99  7]
 [ 1  2]]

Original matrix after modifying 'view_slice':
[[99  7  0]
 [ 1  2  7]
 [ 1  8  5]]


In [3]:
#Q.78:- create a NumPy array 'array'_a' of shape(4,3) with sequential integers from 1 to 12. Extract a slice 'view_b'from 'array_a'and broadcast the addition of 5 to view_b .Check if it alters the original 'array_a'.
#Ans:-
import numpy as np

# Create a NumPy array 'array_a' of shape (4, 3) with sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape(4, 3)

print("Original array (array_a):")
print(array_a)

# Extract a slice 'view_b' from 'array_a'
# For example, take the entire array as the slice (view_b)
view_b = array_a[:]

print("\nSlice (view_b) before modification:")
print(view_b)

# Broadcast the addition of 5 to 'view_b'
view_b += 5

print("\nSlice (view_b) after adding 5:")
print(view_b)

print("\nOriginal array (array_a) after modifying 'view_b':")
print(array_a)


Original array (array_a):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Slice (view_b) before modification:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Slice (view_b) after adding 5:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]

Original array (array_a) after modifying 'view_b':
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [4]:
# Q.79:-Create a NumPy array 'orig_array' of shape (2,4) with values from 1 to 8. Create a reshaped view 'reshaped_view'of shape(4,2) from orig_array. Modify an elememt in 'reshaped_view' and check if it reflects changes in the original 'orig_array'
#Ams:-
import numpy as np

# Create a NumPy array 'orig_array' of shape (2, 4) with values from 1 to 8
orig_array = np.arange(1, 9).reshape(2, 4)

print("Original array (orig_array):")
print(orig_array)

# Create a reshaped view 'reshaped_view' of shape (4, 2) from 'orig_array'
reshaped_view = orig_array.reshape(4, 2)

print("\nReshaped view (reshaped_view) before modification:")
print(reshaped_view)

# Modify an element in 'reshaped_view'
reshaped_view[0, 0] = 99

print("\nReshaped view (reshaped_view) after modification:")
print(reshaped_view)

print("\nOriginal array (orig_array) after modifying 'reshaped_view':")
print(orig_array)


Original array (orig_array):
[[1 2 3 4]
 [5 6 7 8]]

Reshaped view (reshaped_view) before modification:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Reshaped view (reshaped_view) after modification:
[[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]

Original array (orig_array) after modifying 'reshaped_view':
[[99  2  3  4]
 [ 5  6  7  8]]


In [7]:
#Q.80: Create a NumPy array 'data' of shape(3,4) with random integers.Extract a copy 'data_copy' of elements greater than 5.Modify an elemnet in 'data_copy' and verify if it affects the original 'data'.
#Ans:-
import numpy as np

# Create a NumPy array 'data' of shape (3, 4) with random integers between 1 and 10
data = np.random.randint(1, 10, size=(3, 4))

print("Original array (data):")
print(data)

# Extract elements greater than 5 and create a copy
# First, create a boolean mask for elements greater than 5
mask = data > 5

# Extract elements greater than 5 using the mask and create a copy
data_copy = data[mask].copy()

print("\nData copy (data_copy) before modification:")
print(data_copy)

# Modify an element in 'data_copy'
data_copy[0] = 99  # Example modification

print("\nData copy (data_copy) after modification:")
print(data_copy)

# Verify if it affects the original 'data'
print("\nOriginal array (data) after modifying 'data_copy':")
print(data)




Original array (data):
[[4 2 1 3]
 [2 4 7 8]
 [5 5 2 8]]

Data copy (data_copy) before modification:
[7 8 8]

Data copy (data_copy) after modification:
[99  8  8]

Original array (data) after modifying 'data_copy':
[[4 2 1 3]
 [2 4 7 8]
 [5 5 2 8]]


In [8]:
# Q.81:- Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.
#Ans:-
import numpy as np

# Create two matrices A and B of identical shape (e.g., 3x3) with integers
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

# Perform addition
addition_result = A + B
print("\nAddition (A + B):")
print(addition_result)

# Perform subtraction
subtraction_result = A - B
print("\nSubtraction (A - B):")
print(subtraction_result)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Addition (A + B):
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction (A - B):
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [9]:
#Q.82:-Generate two matrices 'C'(3*2) and 'D'(2*4) and perform matrix multiplication.

#Ans:-
import numpy as np

# Generate two matrices C (3x2) and D (2x4) with random integers
C = np.random.randint(1, 10, size=(3, 2))
D = np.random.randint(1, 10, size=(2, 4))

print("Matrix C (3x2):")
print(C)

print("\nMatrix D (2x4):")
print(D)

# Perform matrix multiplication
result = C @ D  # or use np.matmul(C, D)

print("\nMatrix multiplication result (C @ D):")
print(result)


Matrix C (3x2):
[[2 3]
 [9 2]
 [4 8]]

Matrix D (2x4):
[[4 2 9 4]
 [1 2 9 7]]

Matrix multiplication result (C @ D):
[[ 11  10  45  29]
 [ 38  22  99  50]
 [ 24  24 108  72]]


In [10]:
#Q.83:- Create a matrix 'E' and find its transpose.
#ans:-
import numpy as np

# Create a matrix 'E' with arbitrary values
E = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("Original matrix E:")
print(E)

# Find the transpose of matrix 'E'
E_transpose = E.T  # or use np.transpose(E)

print("\nTranspose of matrix E:")
print(E_transpose)


Original matrix E:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of matrix E:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [11]:
#Q.84:- Generate a square matrix 'F' and compute its determinant.
# Ans:-
import numpy as np

# Generate a square matrix 'F' of size 3x3 with random integers
F = np.random.randint(1, 10, size=(3, 3))

print("Square matrix F:")
print(F)

# Compute the determinant of matrix 'F'
determinant = np.linalg.det(F)

print("\nDeterminant of matrix F:")
print(determinant)


Square matrix F:
[[7 2 5]
 [7 8 5]
 [5 7 7]]

Determinant of matrix F:
143.9999999999999


In [12]:
#Q.85:- Create a square matrix 'G' and find its inverse.
#Ans:-
import numpy as np

# Create a square matrix 'G' of size 3x3 with random integers
G = np.random.randint(1, 10, size=(3, 3))

print("Square matrix G:")
print(G)

# Compute the determinant to check if the matrix is invertible
determinant = np.linalg.det(G)

# Compute the inverse of matrix 'G' if the determinant is not zero
if determinant != 0:
    G_inverse = np.linalg.inv(G)
    print("\nInverse of matrix G:")
    print(G_inverse)
else:
    print("\nMatrix G is singular and does not have an inverse.")


Square matrix G:
[[5 1 5]
 [7 4 2]
 [7 8 4]]

Inverse of matrix G:
[[ 0.          0.28571429 -0.14285714]
 [-0.11111111 -0.11904762  0.1984127 ]
 [ 0.22222222 -0.26190476  0.1031746 ]]
